# Generated by Django 6.0.2 on 2026-03-02 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_note',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spec1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spec2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spec3',
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Advanced Technology'", max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the feature')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order for features')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_features', to='products.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g., 'Power Output', 'Speed', 'Voltage'", max_length=255)),
                ('value', models.CharField(help_text="e.g., '500W', '3000 RPM', '220V'", max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order for specs')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Specs',
                'ordering': ['order'],
            },
        ),
    ]
