# Generated by Django 6.0.2 on 2026-03-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_availability_remove_product_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={},
        ),
        migrations.AlterModelOptions(
            name='spec',
            options={'verbose_name_plural': 'Specs'},
        ),
        migrations.RemoveField(
            model_name='feature',
            name='order',
        ),
        migrations.RemoveField(
            model_name='spec',
            name='order',
        ),
    ]
