# Generated by Django 6.0.2 on 2026-03-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Catalog Request',
                'verbose_name_plural': 'Catalog Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
